delete
N-Viet-ruby-dev/qa-intern-batch-3 pull request #17
Opened 2019-08-06 10:27 UTC by CH1006

http://192.168.100.19:3333/issues/68

2019-08-06 11:00 UTC, luongvietdung commented on app/controllers/application_controller.rb
> +  def is_admin?
Hàm này dùng ở đâu

2019-08-06 11:02 UTC, CH1006 commented on app/controllers/application_controller.rb
> +  def is_admin?
em dùng trong controllers/admin/base_controller.rb

2019-08-07 01:38 UTC, luongvietdung commented on app/assets/javascripts/admin/custom.js
> +    var x = document.getElementsByClassName("dataTables_scrollHeadInner");
Dùng CSS mà định nghĩa width 100%, 
Hạn chế dùng JS để định nghĩa CSS nhất có thể 
Mà sử dụng Jquery để viết chứ

Tương tự những chỗ khác

2019-08-07 01:38 UTC, luongvietdung commented on app/controllers/application_controller.rb
> +  def is_admin?
Chỉ có hàm trả về true false mới có dấu hỏi chấm
Nếu chỉ dùng trong đó thì viết trong base_controller

2019-08-07 01:38 UTC, luongvietdung commented on app/models/user.rb
> -  validate :avatar_presence
Sao lại xoá đi thế em

2019-08-07 01:40 UTC, CH1006 commented on app/models/user.rb
> -  validate :avatar_presence
tại em nghĩ avatar có thể cho nil được, sau người dùng có thể update lại trong profile

2019-08-07 01:46 UTC, CH1006 commented on app/controllers/application_controller.rb
> +  def is_admin?
base_controller em dùng để gọi layout của trang admin, cho nên em phải làm vậy, nếu em viết method này trong đó thì em phải đặt before_action cho mỗi controller kế thừa từ nó, nên em làm vậy cho gọn ạ

2019-08-07 01:47 UTC, CH1006 commented on app/assets/javascripts/admin/custom.js
> +    var x = document.getElementsByClassName("dataTables_scrollHeadInner");
chỗ này `datatable` nó không

2019-08-07 02:06 UTC, luongvietdung commented on app/models/user.rb
> -  validate :avatar_presence
OK em

2019-08-07 02:10 UTC, CH1006 commented
ready

2019-08-07 03:13 UTC, luongvietdung requested changes

2019-08-07 03:13 UTC, luongvietdung commented on app/controllers/admin/base_controller.rb
> +      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
Nếu chỉ có 1 format thì không cần respond_to làm gì 
render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found thẳng luôn

Mà anh nghĩ là ở đây raise exception rồi ở application controller sẽ rescure và render 404 sẽ tổng quát hơn

2019-08-07 03:13 UTC, luongvietdung commented on app/controllers/admin/users_controller.rb
> +      format.js { render :js => "window.location.href = '#{admin_users_path}'"
Cái này thì viết luôn trong hàm update đi. Dùng callback làm gì?

2019-08-07 04:41 UTC, CH1006 commented
ready

2019-08-07 06:02 UTC, luongvietdung approved these changes

2019-08-07 06:02 UTC, merged